# Generated by Django 5.2.8 on 2025-11-22 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название меню')),
                ('title', models.CharField(max_length=100, verbose_name='Название пункта')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='Ссылка (явная)')),
                ('named_url', models.CharField(blank=True, max_length=255, verbose_name='Named URL')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.menuitem', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
            },
        ),
    ]
